export const SET_EXPLORE_ARTIST = 'SET_EXPLORE_ARTIST';
export const SET_EXPLORE_SONG = 'SET_EXPLORE_SONG';
export const SET_EXPLORE_RECOMMENDATIONS = 'SET_EXPLORE_RECOMMENDATIONS';
export const ADD_EXPLORE_RECOMMENDATIONS = 'ADD_EXPLORE_RECOMMENDATIONS';
export const SET_ARTIST_INFO = 'SET_ARTIST_INFO';