export const SET_PROFILE_TOKENS = 'SET_PROFILE_TOKENS';
export const SET_PROFILE_TOP = 'SET_PROFILE_TOP';
export const SET_PROFILE_TOP_TIME_FRAME = 'SET_PROFILE_TOP_TIME_FRAME';
export const SET_PROFILE_RECOMMENDATIONS_TIME_FRAME = 'SET_PROFILE_RECOMMENDATIONS_TIME_FRAME';